### ISSUE TITLE
Rework the pipeline workflow

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#13115]
## Introduction

In order to make the Gitlab CI pipeline easier to adopt and simpler to implement, we have begun work on an "inversion" of the current workflow.  Currently, the spack repo (or a gitlab mirror thereof) is the starting point, and when CI is kicked off on that repo, a custom environment repository (specified in CI environment variables) is cloned.  To "invert" that workflow would mean to make the environment repository the starting point, and when CI is kicked off on _that_ repo, a possible (but not necessarily requisite) first step would be to clone some custom spack repository.  In either view of the workflow, a `.gitlab-ci.yml` is generated and pushed to a downstream CI repository where the build jobs of the main pipeline are run.

The reason for creating this issue is to provide a place to have a conversation regarding this work while it is still in progress, giving adopters a chance to provide feedback/input on the proposed changes.  So please feel free to comment on this issue with your thoughts and suggestions.

### Rationale

Here's how this new workflow might look from the perspective of an as-yet unwritten “Quickstart Guide to Spack Pipelines” to look:

1. Create a repository on your gitlab instance
2. Add a spack.yaml at the root containing your pipeline environment
3. Add a .gitlab-ci.yml at the root containing a single job, similar to this one:

```
  pipeline-job:
    tags:
      - <custom-tag>
      ...
    script:
      - spack ci start
```

4. Add any secrets required by the CI process to environment variables using the CI web ui

We'll refer to that example above throughout this issue description.  The first thing to notice is that we're not forcing users to track any specific upstream spack repo.  In some cases, it could be the case that any runners tagged to match the tags in the job will already have a default spack instance that should be used.  In the job example above, the assumption is that on the runners identified by `<custom-tags>, ...`, the appropriate version of spack will already be loaded and ready to use.  In cases where a custom spack is needed, that information will need to be specified when generating the workload, as well as propagated to all build jobs, and thus a pipeline job like the following might be needed:

```
  pipeline-job:
    tags:
      - <some-other-tag>
      ...
    before_script:
      - pushd <some_temp_dir>
      - git clone ${SPACK_REPO} --branch ${SPACK_REF}
      - popd
      - . <some_temp_dir>/spack/share/spack/setup-env.sh
    script:
      - spack ci start ... --spack-repo ${SPACK_REPO} --spack-ref ${SPACK_REF}
```

### Description

Adding this feature doesn't necessarily require a large re-implementation of the pipeline functionality we have currently.  Instead, it represents a change in the way we think about things, it moves some responsibility and control around, and it requires that we do some work to re-organize things.  Some tradeoffs are inevitable, one example is that instead of needing to clone some custom environment repository in order to find the release environment packages we want to build, we may instead need to clone a custom spack repo as a par of the workflow.  In this case, we put some responsibility (control) in the hands of pipeline adopters to know what spack they want to use in their environment.  Also in this case, it requires that the pipeline infrastructure generates jobs with the ability to clone a custom spack.  Some other tradeoffs are discussed in the sections below.

### Triggering pipelines (also related to PR testing)

There are two broad cases of pipeline triggering that we are keeping in mind:

1. Responding to changes on the spack repo itself.  This could include pushing to a particular branch or creating a PR (including from a fork).
2. Responding to changes on the environment repo (which must necessarily be a gitlab repo if we wish to take advantage of gitlab CI)

All sub-cases of case 1, above, may need to be handled by sending API requests to the gitlab environment repo where pipelines originate.  We will consider the possibilities of using GitHub actions (or similar functionality) to send the API requests to gitlab.  We need to investigate how much flexibility we have on the gitlab side, in terms of dynamically controlling aspects of the pipeline using variables in the request.

Cases falling under 2, above, may be simpler to trigger pipelines on the same repo where the environment is housed.  While multiple repositories are still required (see the next section), gitlab [multi-project pipelines](https://docs.gitlab.com/ee/ci/multi_project_pipelines.html) could be leveraged to handle the triggering between the pre-ci and downstream CI repos.

The tradeoff here is fairly symmetric: it becomes potentially easier to test PRs to the environment repository, at the expense of complicating PR testing on spack itself.

### Effect on the number of repositories required for pipeline testing

Until now (in fact, until at least January 2020) Gitlab CI has not provided the ability to generate jobs dynamically, and our workaround for this has been to use multiple gitlab repositories.  One repository, which we have called the "pre-ci" repository (and which has always been a mirror of the spack repo itself), is used to generate the workload for a second repository which we have called the "downstream ci" repository.  A third repository, which we have called the environment repository, was introduced as a way for pipeline adopters to specify their own custom environment. 

 Adopting this new way of thinking of the workflow would certainly allow us to get rid of one of these repos, the spack mirror.  At that point the environment repository would become the "pre-ci" repo and the "downstream ci" repo could remain unchanged.  When gitlab provides the ability to generate jobs dynamically (as described [here](https://gitlab.com/gitlab-org/gitlab-foss/issues/45828)), we could get rid of the downstream ci repo as well, resulting in just a single repo for build pipelines.  Additionally, at that point the jobs shown above would be replaced with the "seed job" (which could possibly just invoke `spack ci generate`).

The obvious tradeoff of "inverting the workflow" here is that adopters do not need to track upstream spack in any way, and instead of most (if not all) workflows needing to clone a custom environment, now some workflows will need to clone spack (although some will not).

### To-Do List

Things that will need to be done in order to implement this:

- [ ] Create a new `spack ci` command with a set of useful sub-commands (some converted from existing bash scripts):
  * `spack ci start` (as shown in the example above) This would be some kind of meta command that would trigger the whole pipeline process to begin.
  * `spack ci generate` could be invoked by `spack ci start` and would generate the `.gitlab-ci.yml`  (work in progress [here](https://github.com/spack/spack/pull/12854))
  * `spack ci push` could also be invoked by `spack ci start` and would commit/push the generated file to the downstream CI repo (work in progress [here](https://github.com/spack/spack/pull/12854))
  * `spack ci rebuild` would be invoked within the `script` section of a generated build job (work in progress [here](https://github.com/scottwittenburg/spack/tree/rebuild-pkg-to-spack-cmd-take-two))
- [ ] Investigate the various possible means of triggering pipelines, especially using arbitrary variables, as documented [here](https://docs.gitlab.com/ee/ci/triggers/#making-use-of-trigger-variables)
- [ ] Using the `spack-infrastructure` repo, experiment with and document how pipelines can be achieved for the various expected use-cases:
  * release testing for spack repo itself (a spack repo contains the environment file)
  * pipelins for sites
    ** where spack is already installed and available on runners
    ** where some version of spack needs to be cloned

**Comment by scottwittenburg** [comment]
@opadron @zackgalbreath Want to take a look and add your thoughts before I begin soliciting feedback from the wider community?

**Comment by opadron** [comment]
> All sub-cases of case 1, above, may need to be handled by sending API requests to the gitlab environment repo where pipelines originate. We will consider the possibilities of using GitHub actions (or similar functionality) to send the API requests to gitlab. We need to investigate how much flexibility we have on the gitlab side, in terms of dynamically controlling aspects of the pipeline using variables in the request.

I have a vague sense of what you are talking about, here.  It would be nice to explain this section in a bit more detail.

**Comment by scottwittenburg** [comment]
ping @paulbry

**Comment by scottwittenburg** [comment]
ping @dnic

**Comment by scottwittenburg** [comment]
@tgamblin , in order to reduce the burden on the config system, what do you think if I try to refactor `spack ci rebuild` (responsible for checking a spec against a mirror and rebuilding if necessary) into two commands/steps?  

The first would be a `setup` step (which, among other things, builds up a custom config dir, but probably shouldn't be called `configure` exactly).  The second would be a `rebuild` step, which would do the actual rebuild work.  Then I'd generate jobs containing those two steps instead of the current one.  

Regardless of where, exactly, I split the functionality, I think it's probably best if the second command doesn't need to be passed arguments from the first, but rather just uses the config override generated by the first one (or at least just reads some additional file written by it).  This way no real shell logic is required, but I still don't force the config system to contort itself for my use case.

**Comment by scottwittenburg** [comment]
@homerdin

**Comment by scottwittenburg** [comment]
@eugeneswalker

**Comment by scottwittenburg** [comment]
@wspear

**Comment by scottwittenburg** [comment]
@mamelara @jrood-nrel

**Comment by scottwittenburg** [comment]
See [fere](https://github.com/scottwittenburg/sc2019-tutorial-pipeline) for example

**Comment by adrienbernede** [comment]
@scottwittenburg Thank you for this useful feature. This comment aims at providing some feedback upon the expected usage in LLNL/Radiuss case, as well as what I think is currently missing.

As stated before, this features makes spack pipelines "environment focused", as opposed to "spack repo focused".
For me, it means I can have a project embedding some spack environments (for development or testing purpose for example), and a step in Gitlab CI pipeline dedicated to the testing of that environment, and the deployment of the packages it describes.

In particular, I want to apply this in different cluster context. It means that I don’t have total control on the resources or the software stack (as opposed to containers). This leads to 2 requirements which I think are not currently fulfilled:
 - I need to be able to specify external packages, (packages.yaml), and if I remember, you told me this is not ready yet, but definitely planned.
 - I need to be able to configure the generated jobs. This is a bit more complex, hence the following explanations.

Resources usage in Gitlab CI:
Using shell and batch runners in Gitlab CI, I can either run a job on the login node (and potentially allocate resources in that job) or I can have the job executed on a batch allocation.
The latter solution is preferred, because the allocation is handled at the runner level (and configured in the pipeline yaml file), not in the job itself.
In order to benefit from this feature, I would need to configure the jobs generated by spack pipeline feature.
IMO, this could be acheived using "depends" and "includes" keywords. Indeed, we could have each jobs of the generated pipeline "depending on" a standard template ".spack_pipeline_job". By default, the generated pipeline could include a configuration file "spack_pipeline_config.yml", provided by the project, and defining this template. 
At the moment, I only need to add some variables to the jobs, each cluster and project may have different needs, and I think this mechanism allows flexibility without putting too much complexity on spack side.

**Comment by scottwittenburg** [comment]
Thanks for providing some feedback @adrienbernede.  

Regarding external packages, this is definitely planned, but just not implemented yet.  In theory it shouldn't be too hard, we'll just skip creating build jobs for those packages, and when the build jobs are run within the environment, the externals should just be found automatically (I think).  If we don't encounter unforeseen obstacles, this should be straightforward to implement in the pipeline workflow.

Regarding a job template, this is something I was just discussing with @opadron and @tgamblin at SC on Thursday.  At the time, one use-case was for @eugeneswalker, who was looking for a way to keep his containers alive when jobs failed until he could get on and inspect them.  One way to allow that might be for him to specify a custom `after_script` in a job template.

I'm not sure how much effort it would take to make this kind of feature fully generic, I'll have to give some more thought to it and do a little experimentation.  But in general, it's definitely something I'm interested in figuring out.  And I'm pretty sure we can support fairly easily the subset of job syntax you mentioned (depends, includes, variables).

**Comment by adrienbernede** [comment]
@scottwittenburg 
> I'm not sure how much effort it would take to make this kind of feature fully generic
I’m not sure if this should be made generic from the very beginning, It’s interesting to see that we already have two different use cases, and I think we could address both relatively easily.
My idea was simply to add
`  depends: .spack_pipeline_job` to each job and `includes: spack_pipeline_config.yml` to the pipeline file. This would allow @eugeneswalker and me to provide our own template.
My spack_pipeline_config.yml would be:
```yaml
spack_pipeline_job:
  variables:
    SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -p pdebug"
```
and Eugenes’ one:
```yaml
spack_pipeline_job:
  after_script:
    - <some docker related stuff>
```
The main limitation is that there may be some conflict with the generated jobs. For example, "before script" already exists, so it cannot be overwritten. Maybe this is why you would like to make it more generic?

**Comment by scottwittenburg** [comment]
Yes, the `before_script` is a good example.  Since we know the pipeline may generate some steps there, should we assume they can all be done before our steps and thus put ours at the end of the list?  I could imagine a user wanting to completely override that section in their template.

I should point out that you already have the ability to add your own custom variables by placing them in the spack environment file.  They can be put in the `gitlab-ci` section, within any `runner-attributes` section you define in there.

**Comment by tldahlgren** [comment]
I just started working with Adrien on some of his GitLab CI work and find the built-in `before_script` that clones the custom Spack repo for every package in the environment a bit too heavy handed wrt file system usage.

So, fwiw, I'd like to "second" the need for the ability to either provide more flexibility in terms of customizing the actions before `generate` and after `build`.  At this point providing a custom `before_script` to execute before the generated `pipeline.yml` is ignored/overridden.  We'd like the ability, for example, to source a custom spack environment setup that is cloned in a pre-generate `setup` stage and removed in a post-build `cleanup` (or `teardown`) stage) so that all of the packages are build as if we were not using a custom Spack clone.

**Comment by scottwittenburg** [comment]
@tldahlgren @adrienbernede Yes, this sounds like something lots of people will want, and just how we go about it is where there's lots of room for discussion.  It could make sense to schedule a time where we could meet and chat about it.  And/or maybe create an issue where we can put forth the various options and keep a record of the discussion of the various pros/cons of any approach.

fyi @eugeneswalker
