### ISSUE TITLE
hermetic/remoteable/cacheable process executions

### ISSUE THREAD

**Issue by cosmicexplorer** [spack/spack#20407]
*Summary:* **use the pants CLI tools to insert file/directory contents from build steps into a local db, and allow execution against a backend for the [bazel remote execution API](https://github.com/bazelbuild/remote-apis) (remexec API).**

### Rationale

The remexec API is a [single-file protobuf API](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto) with two parts:
- a CAS subset, which encodes files and [directory contents as a merkle tree](https://github.com/bazelbuild/remote-apis/blob/9e72daff42c941baaf43a4c370e2607a984c58a7/build/bazel/remote/execution/v2/remote_execution.proto#L645-L734).
- a process execution subset, which encodes [all of a process's inputs and outputs](https://github.com/bazelbuild/remote-apis/blob/9e72daff42c941baaf43a4c370e2607a984c58a7/build/bazel/remote/execution/v2/remote_execution.proto#L373-L452)

A *client* can send/receive filesystem data to a *server* via CAS API methods. A client can provide a process execution request to a server, which is then executed. **The reason this works remotely is because the process execution request includes every single platform-appropriate file which is required to execute the process as a merkle tree.**  

1. With #20359, spack can avoid hitting the disk entirely after reading a file once.
    - **This would be especially useful for builds on NFS mounts.**
2. Encoding each build step's inputs and outputs allows pulling a process execution from a persistent cache if the inputs haven't changed.
    - **Two instances of Spack on separate nodes which connect to the same remexec backend will immediately fill out each other's caches transitively via syncing with the backend. This removes any requirement for a period monolithic cache mirroring step.**
3. A remote execution backend decouples execution from spack entirely, making it possible to address build step performance separately and directly.
    - **Enables separating all build step execution logic from the spack CLI tool into a remexec backend which runs as a separate process, which allows architecting the backend for build performance without having to change the rest of spack at all.**
    - With #20359 and #20260, spack can perform optimizations with FUSE that use its prior knowledge of the build step, such as dropping unused writes and pre-allocating buffers for large reads. This may drastically improve its performance beyond what any native filesystem would allow. 

Spack is able to build ~all of its dependencies from scratch, so it would be the only implementor of the remexec API which doesn't have a significant implicit dependency on the Linux environment that a process executes in. **Other build tools would need to spend a huge amount of effort to achieve this -- they might as well just use Spack directly.**

### Description

*There was a lot more written in this issue before github lost it.*

The reason this is feasible is because pants provides two command-line tools which together implement the CAS and process execution portions of the API:
- [`fs_util`](https://github.com/pantsbuild/pants/blob/master/src/rust/engine/fs/fs_util/src/main.rs) ingests and materializes local directories from checksummed merkle trees.
- [`process_executor`](https://github.com/pantsbuild/pants/blob/master/src/rust/engine/process_executor/src/main.rs), which retrieves the directory contents from a given checksum and executes a process with the given command line and environment variables.

These tools can be made into a spack package: a mostly-complete first attempt is [here](https://github.com/cosmicexplorer/snippets/blob/main/pants/bootstrap-pants-vfs-utils.bash).

### Additional information: Symbolic Filesystem Changes and the `upc` Library
Pants uses a [very idiosyncratic API](https://www.pantsbuild.org/docs/rules-api-file-system) to manipulate directory contents (e.g. merging directories) "symbolically", modifying only the CAS and not the local fs. We should be able to avoid creating a whole new API to work with files in general, though, because Spack has a pretty well-defined and decoupled "build step" concept. This hopefully allows for these symbolic manipulations to occur in a single, small part of the codebase, without affecting most other code.

`fs_util` does not expose any API to perform these symbolic operations. At first, this *could* be replaceable with real filesystem operations and then handed to `fs_util`, but this will be slow in many cases compared to symbolic manipulation. However, I have already prototyped a runner for these kinds of process execution requests ([entry point](https://github.com/cosmicexplorer/upc/blob/master/local/virtual-cli/client/MainWrapper.scala#L81-L114)) which specify a digest ([virtual fs](https://github.com/cosmicexplorer/upc/blob/master/local/virtual-cli/client/VFS.scala)). The process execution part doesn't work for spack: it doesn't use FUSE, it's jvm-only, and it requires changing the application to use different methods for file operations. However, it is very likely to be useful for mapping out the problem.

### TODO
1. [ ] Make `fs_util` and `process_executor` into a spack package.
2. [ ] Determine the expected input and output files for each build step.
    - `strace` should be able to provide the exact information, but that won't be possible to automate over every configuration of every package, so there will be a long tail of manual effort here.
3. [ ] Use `fs_util` to read every file spack intends to use, and perform symbolic filesystem manipulations to form a coherent `input_digest` for the tool. Read all of a build step's output files with `fs_util` as well.
    - All file information should now be replicated in the CAS.
    - **The `upc` library may be necessary for this step.**
4. [ ] Generate a process execution request class with the merged input digest for each build step, and execute with `process_executor` locally.
    - This forms a feedback loop with (2).
5. [ ] Use the `process_executor` wrapper to create a remexec server, which can be launched as a separate process.
    - Ensure spack can send remote executions to itself locally or remotely.
6. [ ] When #20395 and (maybe) #20260 are done, investigate optimizations the virtual fs can perform with prior knowledge of process inputs and outputs.

**Comment by cosmicexplorer** [comment]
It's not clear yet how useful this would be. The most useful measurements to get first would require picking a package with no dependencies, then asking for that package:
- Which files does each build step (configure, make, install, test, ...) have access to at the start and the end of the step?
- Which files does each build step read, and which does it write? (This can be determined with `strace`.)
- After removing unused files, what is the minimum input necessary for each build step to succeed?
- After removing unused files, how large is the output of the build step?

Then, spack can be made to use `fs_util` and `process_executor` for the selected package's build steps, and iterate until that 
succeeds.

Then, in parallel:
1. Perform the input/output calibration steps above for each package, but merging the dependencies' outputs together by hand to build the package. (Long tail of packages here.)
2. Depend on `upc` and make the output merging into symbolic (faster) operations.
3. Create a remexec backend with `fs_util` and `process_executor` and probably `upc`, and make spack's "local" executions actually spin up a remexec backend daemon.
3. With #20359 and #20260, investigate performance optimizations when input and output files are known beforehand.

**Comment by cosmicexplorer** [comment]
It's also totally possible to do this without using the pants CLI tools or `upc` at all. But I believe the CAS interactions, the remote file sync logic, and the conversion to protobuf (and keeping up with updates to the API) would be a very large project, while this ticket instead describes how to *incrementally* test out parts of the remoting stack.

**Comment by cosmicexplorer** [comment]
I believe I was extremely concerned about being annoying earlier and made up an excuse to close this issue. It describes a fundamentally possible path spack can traverse at some point, even if it's not feasible to consider right now.
